import type { Product, Order, ReferralCode, AccessRequest } from './types';

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-oil-1',
    name: 'Lavender Botanical Elixir',
    slug: 'lavender-botanical-elixir',
    description: 'A soothing full-spectrum oil infused with French lavender, cold-pressed jojoba, and botanical terpenes for profound evening relaxation and restorative sleep.',
    price: 48,
    inventory: 25,
    category: 'Oils',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1Yy6GMbIqi-iQxCvqjcLUfqwsZwkrt1RwcRWsq9LWTMGM2sWHofVCipqrnFTdmiNqF0BxZgRzurPlmSZ0H1_qHIX2EgXTqNjfQcjcuK2s4Xx3yAuJ-_QBo1i06XVliNJMJBxYP_gbqKVPVCFSA6bkTv1oLOQxIQM0Zh-klcrUdkcId8u87rBkqu2lUURTMk0qQO_X5KlbGWgQSN8rdjfBuXHAz2pzalmlqS1j13ztnc0aRaHdnK8OxA',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-oil-2',
    name: 'Eucalyptus Balance Tincture',
    slug: 'eucalyptus-balance-tincture',
    description: 'Refreshing botanical blend with Tasmanian blue eucalyptus, peppermint essence, and MCT oil designed to promote clarity and breathwork harmony.',
    price: 54,
    inventory: 18,
    category: 'Oils',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6KYoMlMURvm17nCxK41HXzRuKdBcC2Det8Yax_tc9aRW1bptic26i0aK8O7LE6jCZd13SHZ_BvCDU2kfS8waEloqtdu_1I1JEPY5AtaezQ6XTubWtsVUw0FTDJbPArCFcFyE5HuRXQe6sLcm9LHlhwMo6fLE_U1D10f_L_ZaPw6K5T69KAcFGL_Y_cxu0gPcJuhwR_cmZkeFNAIdse_MnJ_g5MdFRv6dbOjxvwyxiL3E3E9b1n3zthQ',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-oil-3',
    name: 'Rosemary Focus Essence',
    slug: 'rosemary-focus-essence',
    description: 'Invigorating organic rosemary tincture micro-distilled for heightened concentration, grounding mindfulness, and afternoon vitality.',
    price: 42,
    inventory: 30,
    category: 'Oils',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1Yy6GMbIqi-iQxCvqjcLUfqwsZwkrt1RwcRWsq9LWTMGM2sWHofVCipqrnFTdmiNqF0BxZgRzurPlmSZ0H1_qHIX2EgXTqNjfQcjcuK2s4Xx3yAuJ-_QBo1i06XVliNJMJBxYP_gbqKVPVCFSA6bkTv1oLOQxIQM0Zh-klcrUdkcId8u87rBkqu2lUURTMk0qQO_X5KlbGWgQSN8rdjfBuXHAz2pzalmlqS1j13ztnc0aRaHdnK8OxA',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-edible-1',
    name: 'Wild Berry Botanical Pastilles',
    slug: 'wild-berry-botanical-pastilles',
    description: 'Artisanal vegan gummies infused with wild blackberry puree, chamomile extract, and magnesium for serene holistic wellness.',
    price: 36,
    inventory: 40,
    category: 'Edibles',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoSHUT8V8JvKKelG1Oc-mBK735DZvZGftkufgqbRYa9UpVmIu-DeKkjpp_B5C_VtWTTySsW3JxbPKsk0TR7l-kLLYVpOsUIsFkn-s317dsJ-j3zoqHsz3Imi0n_ArtGx_6T_J7bB6wKw-TqEAHtxnKbutmCXJHf02jvaRPX-CSlJkCW_c6plXN7OEj5zEOy7cuEXL8fUoElj-6UmS9sV762gaxVnq1Ar4RNov77DwrwD9XY-tqsj3-Yg',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-edible-2',
    name: 'Citrus Glow Herbal Chews',
    slug: 'citrus-glow-herbal-chews',
    description: 'Cold-pressed yuzu and blood orange botanical chews loaded with vitamin C, lion mane mushroom extract, and organic ginger.',
    price: 32,
    inventory: 22,
    category: 'Edibles',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoSHUT8V8JvKKelG1Oc-mBK735DZvZGftkufgqbRYa9UpVmIu-DeKkjpp_B5C_VtWTTySsW3JxbPKsk0TR7l-kLLYVpOsUIsFkn-s317dsJ-j3zoqHsz3Imi0n_ArtGx_6T_J7bB6wKw-TqEAHtxnKbutmCXJHf02jvaRPX-CSlJkCW_c6plXN7OEj5zEOy7cuEXL8fUoElj-6UmS9sV762gaxVnq1Ar4RNov77DwrwD9XY-tqsj3-Yg',
    is_active: true,
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-edible-3',
    name: 'Dark Chocolate Mint Calming Bites',
    slug: 'dark-chocolate-mint-calming-bites',
    description: 'Single-origin 72% Ecuadorian cacao infused with fresh garden mint and ashwagandha adaptogens for blissful evening unwinding.',
    price: 38,
    inventory: 15,
    category: 'Edibles',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoSHUT8V8JvKKelG1Oc-mBK735DZvZGftkufgqbRYa9UpVmIu-DeKkjpp_B5C_VtWTTySsW3JxbPKsk0TR7l-kLLYVpOsUIsFkn-s317dsJ-j3zoqHsz3Imi0n_ArtGx_6T_J7bB6wKw-TqEAHtxnKbutmCXJHf02jvaRPX-CSlJkCW_c6plXN7OEj5zEOy7cuEXL8fUoElj-6UmS9sV762gaxVnq1Ar4RNov77DwrwD9XY-tqsj3-Yg',
    is_active: true,
    created_at: new Date().toISOString(),
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-84920',
    user_id: '@elena_walker',
    total: 86000,
    status: 'Pending Verification',
    created_at: new Date(Date.now() - 3600000 * 2).toISOString(),
    shipping_address: {
      instagramHandle: '@elena_walker',
      phone: '+234 802 333 4444',
      region: 'Maitama',
      address: 'Plot 722, Gana Street, near Transcorp Hilton',
      city: 'Abuja',
      state: 'FCT',
    },
    receipt_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6KYoMlMURvm17nCxK41HXzRuKdBcC2Det8Yax_tc9aRW1bptic26i0aK8O7LE6jCZd13SHZ_BvCDU2kfS8waEloqtdu_1I1JEPY5AtaezQ6XTubWtsVUw0FTDJbPArCFcFyE5HuRXQe6sLcm9LHlhwMo6fLE_U1D10f_L_ZaPw6K5T69KAcFGL_Y_cxu0gPcJuhwR_cmZkeFNAIdse_MnJ_g5MdFRv6dbOjxvwyxiL3E3E9b1n3zthQ',
    items: [
      {
        id: 'prod-oil-1',
        name: 'Lavender Botanical Elixir',
        variant: '30ml / 500mg',
        price: 48000,
        quantity: 1,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1Yy6GMbIqi-iQxCvqjcLUfqwsZwkrt1RwcRWsq9LWTMGM2sWHofVCipqrnFTdmiNqF0BxZgRzurPlmSZ0H1_qHIX2EgXTqNjfQcjcuK2s4Xx3yAuJ-_QBo1i06XVliNJMJBxYP_gbqKVPVCFSA6bkTv1oLOQxIQM0Zh-klcrUdkcId8u87rBkqu2lUURTMk0qQO_X5KlbGWgQSN8rdjfBuXHAz2pzalmlqS1j13ztnc0aRaHdnK8OxA',
      },
      {
        id: 'prod-edible-3',
        name: 'Dark Chocolate Mint Calming Bites',
        variant: '120g Box',
        price: 38000,
        quantity: 1,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoSHUT8V8JvKKelG1Oc-mBK735DZvZGftkufgqbRYa9UpVmIu-DeKkjpp_B5C_VtWTTySsW3JxbPKsk0TR7l-kLLYVpOsUIsFkn-s317dsJ-j3zoqHsz3Imi0n_ArtGx_6T_J7bB6wKw-TqEAHtxnKbutmCXJHf02jvaRPX-CSlJkCW_c6plXN7OEj5zEOy7cuEXL8fUoElj-6UmS9sV762gaxVnq1Ar4RNov77DwrwD9XY-tqsj3-Yg',
      },
    ],
  },
  {
    id: 'ord-84919',
    user_id: '@marcus_botanica',
    total: 86000,
    status: 'Processing',
    created_at: new Date(Date.now() - 3600000 * 14).toISOString(),
    shipping_address: {
      instagramHandle: '@marcus_botanica',
      phone: '+234 812 555 7890',
      region: 'Asokoro',
      address: '18 Yakubu Gowon Crescent, Asokoro',
      city: 'Abuja',
      state: 'FCT',
    },
    receipt_url: '',
    items: [
      {
        id: 'prod-oil-2',
        name: 'Eucalyptus Balance Tincture',
        variant: '30ml / 750mg',
        price: 54000,
        quantity: 1,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB6KYoMlMURvm17nCxK41HXzRuKdBcC2Det8Yax_tc9aRW1bptic26i0aK8O7LE6jCZd13SHZ_BvCDU2kfS8waEloqtdu_1I1JEPY5AtaezQ6XTubWtsVUw0FTDJbPArCFcFyE5HuRXQe6sLcm9LHlhwMo6fLE_U1D10f_L_ZaPw6K5T69KAcFGL_Y_cxu0gPcJuhwR_cmZkeFNAIdse_MnJ_g5MdFRv6dbOjxvwyxiL3E3E9b1n3zthQ',
      },
      {
        id: 'prod-edible-2',
        name: 'Citrus Glow Herbal Chews',
        variant: '60g Pouch',
        price: 32000,
        quantity: 1,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBoSHUT8V8JvKKelG1Oc-mBK735DZvZGftkufgqbRYa9UpVmIu-DeKkjpp_B5C_VtWTTySsW3JxbPKsk0TR7l-kLLYVpOsUIsFkn-s317dsJ-j3zoqHsz3Imi0n_ArtGx_6T_J7bB6wKw-TqEAHtxnKbutmCXJHf02jvaRPX-CSlJkCW_c6plXN7OEj5zEOy7cuEXL8fUoElj-6UmS9sV762gaxVnq1Ar4RNov77DwrwD9XY-tqsj3-Yg',
      },
    ],
  },
  {
    id: 'ord-84915',
    user_id: '@sophia_wellness',
    total: 96000,
    status: 'Delivered',
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    shipping_address: {
      instagramHandle: '@sophia_wellness',
      phone: '+234 809 111 8888',
      region: 'Wuse',
      address: '22 Aminu Kano Crescent, Wuse II',
      city: 'Abuja',
      state: 'FCT',
    },
    receipt_url: '',
    items: [
      {
        id: 'prod-oil-1',
        name: 'Lavender Botanical Elixir',
        variant: '30ml / 500mg',
        price: 48,
        quantity: 2,
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD1Yy6GMbIqi-iQxCvqjcLUfqwsZwkrt1RwcRWsq9LWTMGM2sWHofVCipqrnFTdmiNqF0BxZgRzurPlmSZ0H1_qHIX2EgXTqNjfQcjcuK2s4Xx3yAuJ-_QBo1i06XVliNJMJBxYP_gbqKVPVCFSA6bkTv1oLOQxIQM0Zh-klcrUdkcId8u87rBkqu2lUURTMk0qQO_X5KlbGWgQSN8rdjfBuXHAz2pzalmlqS1j13ztnc0aRaHdnK8OxA',
      },
    ],
  },
];

export const MOCK_REFERRAL_CODES: ReferralCode[] = [
  {
    id: 'ref-1',
    code: 'botanica1',
    owner_handle: '@jane_wellness',
    owner_email: 'jane@example.com',
    is_active: true,
    created_at: new Date('2023-10-20').toISOString(),
  },
  {
    id: 'ref-2',
    code: 'wellness2',
    owner_handle: '@john_botanicals',
    owner_email: 'john@example.com',
    is_active: true,
    created_at: new Date('2023-10-21').toISOString(),
  },
];

export const MOCK_ACCESS_REQUESTS: AccessRequest[] = [
  {
    id: 'ar-1',
    instagram_handle: '@alice_herbal',
    phone: '+234 802 333 4444',
    referral_code: 'botanica1',
    referred_by: '@jane_wellness',
    status: 'pending',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'ar-2',
    instagram_handle: '@bob_rituals',
    phone: '+234 811 555 6666',
    referral_code: 'wellness2',
    referred_by: '@john_botanicals',
    status: 'approved',
    reviewed_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    reviewed_by: 'admin@botanica.com',
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
];


